export const noMilestone = "No Milestone"
export const noLabels = "No Labels"
export const noAssignees = "No Assignees"
export const noIssuesToReport = "No issues to report"
export const attributionText = "This report was created with Snitch 👉"
export const snitchUrl = "https://github.com/4awpawz/snitch"
